[package]
name = "mylib"
version = "0.1.0"
edition = "2024"

[dependencies]
# --- play = { path = "../play" }
strum = "0.27.2"
# --- Abhängigkeiten für das Modul 'dates' ---
chrono = "0.4.42"
# --- Abhängigkeiten für das Untermodul 'dates::astrology' ---
chrono-tz = "0.10.4"  # Ermöglicht IANA-Zeitzonen-Datenbanken (z. B. "Europe/Vienna")
# --- Abhängigkeiten für das Untermodul 'dates::astronomy' ---
vsop87 = "3.0"     # Berechnet mathematisch exakte Planeten- und Sonnenpositionen
